config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ochre-vole.sh
        container: qc.acc_greasy-apricot-hare
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-burgundy-frise.sh
        container: qc.doc_ready-eggplant-mandrill
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cardinal-dhole.sh
        container: qc.doc_sloppy-zucchini-dachshund
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-crimson-seal.sh
        container: qc.doc_skanky-amaranth-gecko
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-magnolia-chameleon.sh
        container: qc.lic_droopy-cyan-rattlesnake
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-lime-wasp.sh
        container: qc.sec_slaphappy-denim-kiwi
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-corn-wolverine.sh
        container: qc.sty_geeky-linen-indri
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-tangerine-spaniel.sh
        container: qc.sty_dorky-wisteria-dalmatian
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-cornflower-fousek.sh
        container: qc.ver_lousy-magnolia-collie
timeout: 5400
