config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lavender-uguisu.sh
        container: qc.acc_muggy-peach-eagle
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-cardinal-zorse.sh
        container: qc.doc_fuzzy-cerise-ant
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-periwinkle-chimpanzee.sh
        container: qc.doc_nippy-mustard-spitz
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-violet-abyssinian.sh
        container: qc.doc_nippy-amethyst-leopard
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-apricot-caracal.sh
        container: qc.lic_muzzy-eggplant-macaque
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-smalt-zonkey.sh
        container: qc.sec_muggy-wheat-ferret
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-pear-magpie.sh
        container: qc.sty_slimy-silver-bullfrog
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-carmine-barb.sh
        container: qc.sty_gimpy-cerulean-numbat
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-purple-chamois.sh
        container: qc.ver_homey-chartreuse-ant
timeout: 5400
