config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-eggplant-squirrel.sh
        container: qc.acc_breezy-chestnut-toucan
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-white-neanderthal.sh
        container: qc.doc_lanky-wisteria-heron
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-magenta-sheepdog.sh
        container: qc.doc_snippy-lemon-rattlesnake
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cobalt-eel.sh
        container: qc.doc_hasty-goldenrod-macaque
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-red-dalmatian.sh
        container: qc.lic_breezy-alizarin-zorse
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-celadon-capuchin.sh
        container: qc.sec_muggy-saffron-emu
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-red-jellyfish.sh
        container: qc.sty_ready-charcoal-spitz
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-lilac-tetra.sh
        container: qc.sty_nippy-myrtle-neanderthal
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-green-caiman.sh
        container: qc.ver_zippy-dandelion-frise
timeout: 5400
