config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-eggplant-barb.sh
        container: qc.acc_homey-black-urchin
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-white-avocet.sh
        container: qc.doc_skinny-bronze-grasshopper
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-mustard-fish.sh
        container: qc.doc_sloppy-sepia-kingfisher
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brass-zonkey.sh
        container: qc.doc_goopy-zucchini-barracuda
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.randy-lavender-paradise.sh
        container: qc.lic_squirrely-brass-chicken
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-goldenrod-lynx.sh
        container: qc.sec_pokey-burgundy-fossa
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-goldenrod-sponge.sh
        container: qc.sty_woolly-cinnabar-wolfhound
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-cyan-macaw.sh
        container: qc.sty_flaky-russet-newt
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-heliotrope-heron.sh
        container: qc.ver_wheezy-goldenrod-booby
timeout: 5400
