config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-taupe-cow.sh
        container: qc.acc_chewy-ecru-tarsier
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-salmon-squirt.sh
        container: qc.doc_sleepy-orange-chipmunk
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-purple-spaniel.sh
        container: qc.doc_gummy-green-swan
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-myrtle-urchin.sh
        container: qc.doc_zippy-orchid-guppy
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-alizarin-stingray.sh
        container: qc.lic_gimpy-auburn-jackal
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-olive-skunk.sh
        container: qc.sec_stuffy-goldenrod-mammoth
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-white-bandicoot.sh
        container: qc.sty_snappy-sepia-angelfish
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lemon-bordeaux.sh
        container: qc.sty_frumpy-auburn-otter
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-bistre-octopus.sh
        container: qc.ver_slaphappy-harlequin-koala
timeout: 5400
