config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-tomato-raccoon.sh
        container: qc.acc_crappy-grey-flounder
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amber-discus.sh
        container: qc.doc_grumpy-mauve-tang
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-asparagus-tuatara.sh
        container: qc.doc_chummy-seashell-opossum
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-saffron-uakari.sh
        container: qc.doc_freaky-green-hyena
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lime-cassowary.sh
        container: qc.lic_crabby-chestnut-russel
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-bronze-bee.sh
        container: qc.sec_gimpy-persimmon-abyssinian
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-linen-monster.sh
        container: qc.sty_sleazy-turquoise-labradoodle
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-sapphire-cheetah.sh
        container: qc.sty_dorky-charcoal-wrasse
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cyan-donkey.sh
        container: qc.ver_clammy-aqua-grasshopper
timeout: 5400
