config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-viridian-dhole.sh
        container: qc.acc_beady-celadon-gecko
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-chestnut-mole.sh
        container: qc.doc_jumpy-cinnabar-caracal
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-pear-mastiff.sh
        container: qc.doc_ready-cornflower-flounder
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-buff-devil.sh
        container: qc.doc_pretty-pear-eel
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerulean-moose.sh
        container: qc.lic_paltry-fuchsia-hippopotamus
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-apricot-meerkat.sh
        container: qc.sec_messy-mauve-chameleon
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-mau.sh
        container: qc.sty_paltry-cinnamon-foxhound
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-goldenrod-ocelot.sh
        container: qc.sty_muzzy-purple-dalmatian
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-razzmatazz-okapi.sh
        container: qc.ver_boozy-xanthic-giraffe
timeout: 5400
