config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-russet-mist.sh
        container: qc.acc_queasy-corn-fossa
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-maroon-dodo.sh
        container: qc.doc_shaky-ruby-turkey
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-magenta-beaver.sh
        container: qc.doc_craggy-auburn-squirt
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-malachite-macaw.sh
        container: qc.doc_chewy-indigo-octopus
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-zucchini-neanderthal.sh
        container: qc.lic_lovely-pumpkin-duck
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.messy-pink-moth.sh
        container: qc.sec_beady-carmine-blue
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-turquoise-paradise.sh
        container: qc.sty_frumpy-carmine-abyssinian
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-zucchini-fossa.sh
        container: qc.sty_wiggy-blue-llama
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-jade-quail.sh
        container: qc.ver_ugly-cinnabar-shark
timeout: 5400
