config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-wheat-wolverine.sh
        container: qc.acc_flimsy-white-orangutan
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-turquoise-wolfhound.sh
        container: qc.doc_flaky-puce-newt
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-orchid-cattle.sh
        container: qc.doc_hasty-puce-mist
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-heliotrope-rattlesnake.sh
        container: qc.doc_snazzy-smalt-toucan
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cerulean-mole.sh
        container: qc.lic_slimy-chartreuse-devil
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-aquamarine-ostrich.sh
        container: qc.sec_wimpy-bistre-swan
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-vermilion-fousek.sh
        container: qc.sty_messy-amethyst-squirt
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cornflower-maltese.sh
        container: qc.sty_pokey-platinum-whale
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-pumpkin-indri.sh
        container: qc.ver_wiggy-lavender-woodlouse
timeout: 5400
