config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-olive-llama.sh
        container: qc.acc_zippy-wheat-ocelot
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-flax-burmese.sh
        container: qc.doc_tacky-gamboge-hamster
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-myrtle-jellyfish.sh
        container: qc.doc_clammy-vermilion-kangaroo
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cobalt-dunker.sh
        container: qc.doc_whiny-charcoal-saola
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-chocolate-rat.sh
        container: qc.lic_dorky-lavender-bongo
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cinnabar-sheepdog.sh
        container: qc.sec_foggy-carmine-wildebeest
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pear-grouse.sh
        container: qc.sty_nippy-ultramarine-buzzard
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-maroon-lynx.sh
        container: qc.sty_bluesy-corn-dugong
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-lilac-akbash.sh
        container: qc.ver_droopy-azure-uakari
timeout: 5400
