config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-brown-fossa.sh
        container: qc.acc_geeky-goldenrod-labradoodle
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-beige-bison.sh
        container: qc.doc_shaky-chestnut-blue
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-silver-blue.sh
        container: qc.doc_boozy-scarlet-wolverine
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-amethyst-macaque.sh
        container: qc.doc_silly-thistle-elephant
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pink-millipede.sh
        container: qc.lic_frumpy-smalt-chin
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-violet-shrew.sh
        container: qc.sec_whiny-teal-swan
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ecru-mist.sh
        container: qc.sty_gummy-charcoal-stoat
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pear-cassowary.sh
        container: qc.sty_tacky-russet-ragdoll
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-auburn-dolphin.sh
        container: qc.ver_snoopy-cerise-quail
timeout: 5400
