config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-mustard-axolotl.sh
        container: qc.acc_dorky-bistre-retriever
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-silver-barb.sh
        container: qc.doc_sloppy-brass-mayfly
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-coral-quokka.sh
        container: qc.doc_stealthy-khaki-coral
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-jade-pinscher.sh
        container: qc.doc_muzzy-xanthic-hippopotamus
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-ochre-camel.sh
        container: qc.lic_woolly-azure-mule
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ruby-booby.sh
        container: qc.sec_stinky-chestnut-snail
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-persimmon-bullfrog.sh
        container: qc.sty_dorky-silver-ant
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-dandelion-crab.sh
        container: qc.sty_nippy-chestnut-lemming
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-taupe-squirrel.sh
        container: qc.ver_flabby-celadon-impala
timeout: 5400
