config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/claudiopica/HiRep:
      branch: master
      repo: https://github.com/claudiopica/HiRep
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-wisteria-earwig.sh
        container: qc.acc_zippy-dandelion-sponge
  QC.Doc:
    repos:
      github.com/claudiopica/HiRep find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-amber-mongrel.sh
        container: qc.doc_lousy-seashell-blue
      github.com/claudiopica/HiRep git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-buff-coral.sh
        container: qc.doc_stinky-puce-macaw
      github.com/claudiopica/HiRep markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-celadon-nightingale.sh
        container: qc.doc_stinky-pink-spaniel
  QC.Lic:
    repos:
      github.com/claudiopica/HiRep licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-emerald-schnauzer.sh
        container: qc.lic_gloppy-saffron-bombay
  QC.Sec:
    repos:
      github.com/claudiopica/HiRep bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-chocolate-setter.sh
        container: qc.sec_woozy-amber-millipede
  QC.Sty:
    repos:
      github.com/claudiopica/HiRep flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-cobalt-cockroach.sh
        container: qc.sty_cheeky-emerald-monkey
      github.com/claudiopica/HiRep hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-peach-greyhound.sh
        container: qc.sty_squeaky-buff-wrasse
  QC.Ver:
    repos:
      github.com/claudiopica/HiRep get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-black-antelope.sh
        container: qc.ver_nerdy-harlequin-coati
timeout: 5400
